// Mentor roster for the consultation tool.
// `tags` drive the major search. `detailed: true` mentors have a full ID-card profile.
// Photo + logo paths point up one level to the site's shared /images.

const IMG = "../images/Mentors/";
const LOGO = "../images/Logos/";

export const mentors = [
  {
    id: "fidel", name: "Fidel Hon", intl: "International", pinned: true,
    role: "Category Analyst", company: "Stuart Alexander",
    uni: "The University of Sydney", degree: "Bachelor of Commerce",
    major: "Marketing and Finance", industry: "FMCG", rate: "Co-founder",
    visa: "485 - Temporary Graduate Visa", gradYear: "2024",
    specialiseIn: ["Analytics"],
    photo: IMG + "fidel new.jpg",
    logos: [{ src: LOGO + "Stuart-Alexander.png", alt: "Stuart Alexander" }, { src: LOGO + "Nestle.png", alt: "Nestlé" }],
    tags: ["marketing", "finance", "fmcg", "business", "commerce", "analytics"],
    bestFor: "Students who want targeted, practical job-search strategies.",
    detailed: true,
    lead: "Fidel started his career after graduating from the University of Sydney and now works as a Category Analyst. He has first-hand experience navigating the job market as an international student.",
    why: "Fidel understands the challenges of visa constraints and language barriers, and is driven to uplift others going through the same path.",
    different: "As the founder of Headstart, he works across every industry through his mentors, so he sees what actually gets people hired regardless of the field. The common denominator is always the same: be a solid candidate on paper, and be someone people want to work with. He can teach anyone how to do both.",
  },
  {
    id: "aidan", name: "Aiden Wibrata", intl: "International",
    role: "Demand Planner", company: "Prysmian",
    uni: "The University of Sydney", degree: "Bachelor of Commerce",
    major: "Information System and Design", industry: "Supply Chain / FMCG / Startup", rate: "$40",
    visa: "485 - Temporary Graduate Visa", gradYear: "2024",
    specialiseIn: ["Supply Chain", "UX / UI", "Analytics"],
    photo: IMG + "aiden new.jpg",
    logos: [{ src: LOGO + "prysmain.webp", alt: "Prysmian" }, { src: LOGO + "Nestle.png", alt: "Nestlé" }],
    tags: ["information systems", "supply chain", "demand planning", "ux", "ui", "analytics", "manufacturing", "fmcg", "tech", "startup"],
    bestFor: "Students who look fine on paper but blend in during interviews and need to learn how to stand out as a person.",
    detailed: true,
    lead: "Aidan studied Information Systems and Design, interned at Nestlé, and now works as a Demand Planner at Prysmian, a cable manufacturing company.",
    why: "He had no real mentors during his own job search, and credits the mentors he did have in sports, studies, and life with every other win he's had. He wants to be that person for students stuck in the job search.",
    different: "He coaches mentees to be memorable on a personal level before they ever pitch their CV. He landed his current job by talking sports with the recruiter, and he teaches the same playbook: strategic questions, real rapport, then the work pitch.",
  },
  {
    id: "angelica", name: "Angelica Grace Sutantyo", intl: "International",
    role: "Technology Consultant", company: "Visagio",
    uni: "University of New South Wales", degree: "Bachelor of Commerce",
    major: "Actuarial and Finance", industry: "Consulting / Tech", rate: "$55",
    visa: "485 - Temporary Graduate Visa", gradYear: "2024",
    specialiseIn: ["Consulting", "Tech Consulting"],
    photo: IMG + "angel new.jpg",
    logos: [{ src: LOGO + "Visagio.jpeg", alt: "Visagio" }],
    tags: ["consulting", "tech consulting", "tech", "it", "actuarial", "finance"],
    bestFor: "International students who want to break into tech consulting as a non-local candidate.",
    detailed: true,
    lead: "A UNSW double-degree student from Indonesia, now working full-time as a Consultant at Visagio. She was Event Director at the Indonesian Society for two years, and has tutored academic, actuarial, and insurance courses.",
    why: "She finds it rewarding to help people and understands how hard it can be to break into consulting. She wishes she had a mentor during her own journey.",
    different: "Angelica broke into tech consulting as an international student from Indonesia, so she has been through the exact process you are about to face. She doesn't give textbook advice, she personalises everything to where you are right now and what you are trying to get into. She has also tutored in actuarial, insurance, and academic subjects, so she knows how to actually teach and explain things clearly. And because she got into consulting recently, her knowledge of how firms recruit, what they test, and what they look for is current.",
  },
  {
    id: "khaleel", name: "Khaleel", intl: "Local",
    role: "Finance Graduate", company: "Acciona",
    uni: "University of Melbourne", degree: "Bachelor of Commerce",
    major: "Marketing & Finance", industry: "Finance / Consulting", rate: "$45-50",
    visa: "Domestic", gradYear: "2025",
    specialiseIn: ["Finance", "Consulting"],
    photo: IMG + "khaleel new.jpg",
    logos: [{ src: LOGO + "EY.png", alt: "EY" }, { src: LOGO + "Acciona.png", alt: "Acciona" }],
    tags: ["finance", "consulting", "marketing", "big 4", "commerce"],
    bestFor: "Finance and consulting students going through graduate program applications, especially those new to Australia.",
    detailed: true,
    lead: "Khaleel moved from Kenya to Australia in 2021, completed a double degree at the University of Melbourne, interned at EY and a marketing firm, and ultimately landed three graduate job offers.",
    why: "He would have loved to have someone guide him through the process, and finds it genuinely rewarding to see people win.",
    different: "He has run career coaching sessions, mock assessment centres, and resume workshops at a previous career coaching service, so he knows what the process looks like from a coaching perspective, not just as someone who went through it.",
  },
  {
    id: "raunaq", name: "Raunaq", intl: "International",
    role: "Financial Analyst", company: "University of Sydney",
    uni: "University of Sydney", degree: "Masters of Commerce",
    major: "Professional Accounting", industry: "Finance", rate: "$40-50",
    visa: "485 - Temporary Graduate Visa", gradYear: "2024",
    specialiseIn: ["Finance", "Business Analytics"],
    photo: IMG + "raun new.jpg",
    logos: [{ src: LOGO + "USYD-logo.png", alt: "University of Sydney" }],
    tags: ["finance", "business analytics", "accounting", "audit", "commerce"],
    bestFor: "Finance and audit students breaking into financial analyst or business analytics roles who need help knowing when and how to network.",
    detailed: true,
    lead: "Raunaq graduated from USYD with a Finance degree in 2024 and works as a Financial Analyst at the university's own faculty, with experience as a peer mentor, lead mentor, and faculty ambassador who helped design the university's mentoring program.",
    why: "He spent a lot of time networking and wants to streamline what he learned from it, so more students can access it without going through the same process alone.",
    different: "He has trained in public speaking and counselled at TAFE, so he focuses on how students articulate and present themselves, not just what they put on paper.",
  },
  // ── Not yet detailed (basic search cards only) ──
  {
    id: "koko", name: "Koko Araki", intl: "International",
    role: "Sales & Marketing Graduate", company: "Kimberly-Clark",
    uni: "", degree: "", major: "", industry: "FMCG", rate: "Co-founder",
    photo: IMG + "koko new.jpg", logos: [],
    tags: ["sales", "marketing", "fmcg", "business"],
    bestFor: "Sales and marketing pathways. Similar international student journey to Fidel.",
    detailed: false,
  },
  {
    id: "koda", name: "Koda Edrick", intl: "International",
    role: "Software Engineer", company: "Lumi",
    uni: "", degree: "", major: "", industry: "Software / Tech / Startup", rate: "$40",
    photo: IMG + "koda new.jpg", logos: [],
    tags: ["software engineering", "computer science", "tech", "startup"],
    bestFor: "Tech students and anyone interested in software or startups.",
    detailed: false,
  },
  {
    id: "deepika", name: "Deepika Dhulipati", intl: "International",
    role: "Graduate Finance Officer", company: "Dept. of Social Services",
    uni: "", degree: "", major: "", industry: "Finance / Audit / Consulting", rate: "$40",
    photo: IMG + "deepika new.jpg", logos: [],
    tags: ["finance", "audit", "accounting", "consulting"],
    bestFor: "Finance, audit and accounting pathways. Government and Big Four exposure.",
    detailed: false,
  },
  {
    id: "samuel", name: "Samuel Kember", intl: "Local",
    role: "Graduate Consultant", company: "Oliver Wyman",
    uni: "University of Sydney", degree: "Commerce (Finance) + Engineering", major: "",
    industry: "Consulting", rate: "$40-50",
    photo: "", logos: [],
    tags: ["consulting", "finance", "engineering", "commerce"],
    bestFor: "Consulting and finance pathways. Students needing soft-skills coaching and interview prep.",
    detailed: false,
  },
  {
    id: "woohee", name: "Woo Hee", intl: "Local",
    role: "Graduate Data Scientist", company: "CBA",
    uni: "UNSW", degree: "Data Science", major: "",
    industry: "Tech / Data / Finance", rate: "$60",
    photo: IMG + "wohee.jpg", logos: [],
    tags: ["data science", "data", "tech", "finance"],
    bestFor: "Data science and analytics pathways across tech and finance.",
    detailed: false,
  },
];

export function getMentor(id) {
  return mentors.find((m) => m.id === id);
}
