// Mentor roster for the consultation tool.
// `tags` drive the major search. `detailed: true` mentors have a full ID-card profile.
// `photo` = card thumbnail. `detailPhoto` = full profile page image.

const IMG = "../images/Mentors/";
const DIMG = "../images/Mentor Detiled Profiles/";
const LOGO = "../images/Logos/";

export const mentors = [
  {
    id: "fidel", name: "Fidel Hon", intl: "International", pinned: true,
    role: "Category Analyst", company: "Stuart Alexander",
    uni: "The University of Sydney", degree: "Bachelor of Commerce",
    major: "Marketing and Finance", industry: "FMCG", rate: "Co-founder",
    visa: "485 - Temporary Graduate Visa", gradYear: "2024",
    specialiseIn: ["Analytics", "Marketing"],
    photo: IMG + "fidel new.jpg",
    detailPhoto: DIMG + "Fidel Profile.png",
    logos: [{ src: LOGO + "Stuart-Alexander.png", alt: "Stuart Alexander" }, { src: LOGO + "Nestle.png", alt: "Nestlé" }],
    tags: ["marketing", "finance", "fmcg", "business", "commerce", "analytics"],
    bestFor: "Students who want targeted, practical job-search strategies.",
    detailed: true,
    lead: "Fidel started his career after graduating from the University of Sydney and now works as a Category Analyst. He has first-hand experience navigating the job market as an international student.",
    why: "Fidel understands the challenges of visa constraints and language barriers, and is driven to uplift others going through the same path.",
    different: "As the founder of Headstart, he works across every industry through his mentors, so he sees what actually gets people hired regardless of the field. The common denominator is always the same: be a solid candidate on paper, and be someone people want to work with. He can teach anyone how to do both.",
  },
  {
    id: "aidan", name: "Aidan Wibrata", intl: "International",
    role: "Demand Planner", company: "Prysmian",
    uni: "The University of Sydney", degree: "Bachelor of Commerce",
    major: "Information System and Design", industry: "Supply Chain / FMCG / Startup", rate: "$40",
    visa: "485 - Temporary Graduate Visa", gradYear: "2024",
    specialiseIn: ["Supply Chain", "Analytics"],
    photo: IMG + "aiden new.jpg",
    detailPhoto: DIMG + "Aiden Profile.png",
    logos: [{ src: LOGO + "prysmain.webp", alt: "Prysmian" }, { src: LOGO + "Nestle.png", alt: "Nestlé" }],
    tags: ["information systems", "supply chain", "demand planning", "ux", "ui", "analytics", "manufacturing", "fmcg", "tech", "startup"],
    bestFor: "Students who look fine on paper but blend in during interviews and need to learn how to stand out as a person.",
    detailed: true,
    lead: "Aidan studied Information Systems and Design, interned at Nestlé, and now works as a Demand Planner at Prysmian, a cable manufacturing company.",
    why: "He had no real mentors during his own job search, and credits the mentors he did have in sports, studies, and life with every other win he's had. He wants to be that person for students stuck in the job search.",
    different: "He coaches mentees to be memorable on a personal level before they ever pitch their CV. He landed his current job by talking sports with the recruiter, and he teaches the same playbook: strategic questions, real rapport, then the work pitch.",
  },
  {
    id: "angelica", name: "Angelica Grace Sutantyo", intl: "International",
    role: "Technology Consultant", company: "Visagio",
    uni: "University of New South Wales", degree: "Bachelor of Commerce",
    major: "Actuarial and Finance", industry: "Consulting / Tech", rate: "$55",
    visa: "485 - Temporary Graduate Visa", gradYear: "2024",
    specialiseIn: ["Consulting", "Tech Consulting"],
    photo: IMG + "angel new.jpg",
    detailPhoto: DIMG + "Angelica.png",
    logos: [{ src: LOGO + "Visagio.jpeg", alt: "Visagio" }],
    tags: ["consulting", "tech consulting", "business analyst"],
    bestFor: "International students who want to break into tech consulting as a non-local candidate.",
    detailed: true,
    lead: "A UNSW double-degree student from Indonesia, now working full-time as a Consultant at Visagio. She was Event Director at the Indonesian Society for two years, and has tutored academic, actuarial, and insurance courses.",
    why: "She finds it rewarding to help people and understands how hard it can be to break into consulting. She wishes she had a mentor during her own journey.",
    different: "Angelica broke into tech consulting as an international student from Indonesia, so she has been through the exact process you are about to face. She doesn't give textbook advice, she personalises everything to where you are right now and what you are trying to get into. She has also tutored in actuarial, insurance, and academic subjects, so she knows how to actually teach and explain things clearly. And because she got into consulting recently, her knowledge of how firms recruit, what they test, and what they look for is current.",
  },
  {
    id: "khaleel", name: "Khaleel", intl: "Local",
    role: "Finance Graduate", company: "Acciona",
    uni: "University of Melbourne", degree: "Bachelor of Commerce",
    major: "Marketing & Finance", industry: "Finance / Consulting", rate: "$45-50",
    visa: "Domestic", gradYear: "2025",
    specialiseIn: ["Finance", "Consulting"],
    photo: IMG + "khaleel new.jpg",
    detailPhoto: DIMG + "Khaleel.jpg",
    logos: [{ src: LOGO + "Acciona.png", alt: "Acciona" }],
    tags: ["finance", "consulting", "marketing", "big 4", "commerce"],
    bestFor: "Finance and consulting students going through graduate program applications, especially those new to Australia.",
    detailed: true,
    lead: "Khaleel moved from Kenya to Australia in 2021, completed a double degree at the University of Melbourne, interned at EY and a marketing firm, and ultimately landed three graduate job offers.",
    why: "He would have loved to have someone guide him through the process, and finds it genuinely rewarding to see people win.",
    different: "He has run career coaching sessions, mock assessment centres, and resume workshops at a previous career coaching service, so he knows what the process looks like from a coaching perspective, not just as someone who went through it.",
  },
  {
    id: "raunaq", name: "Raunaq", intl: "International",
    role: "Financial Analyst", company: "University of Sydney",
    uni: "University of Sydney", degree: "Masters of Commerce",
    major: "Professional Accounting", industry: "Finance", rate: "$40-50",
    visa: "485 - Temporary Graduate Visa", gradYear: "2024",
    specialiseIn: ["Finance", "Business Analytics"],
    photo: IMG + "raun new.jpg",
    detailPhoto: DIMG + "Raun.jpg",
    logos: [{ src: LOGO + "USYD-logo.png", alt: "University of Sydney" }],
    tags: ["finance", "business analytics", "accounting", "audit", "commerce"],
    bestFor: "Finance and audit students breaking into financial analyst or business analytics roles who need help knowing when and how to network.",
    detailed: true,
    lead: "Raunaq graduated from USYD with a Finance degree in 2024 and works as a Financial Analyst at the university's own faculty, with experience as a peer mentor, lead mentor, and faculty ambassador who helped design the university's mentoring program.",
    why: "He spent a lot of time networking and wants to streamline what he learned from it, so more students can access it without going through the same process alone.",
    different: "He has trained in public speaking and counselled at TAFE, so he focuses on how students articulate and present themselves, not just what they put on paper.",
  },
  {
    id: "koko", name: "Koko Araki", intl: "International",
    role: "Area Sales Manager", company: "Kimberly-Clark",
    uni: "University of Sydney", degree: "Bachelor of Arts",
    major: "Marketing and Environmental Studies", industry: "FMCG / Marketing / Sales", rate: "Co-founder",
    visa: "485 - Temporary Graduate Visa", gradYear: "2023",
    specialiseIn: ["Marketing", "Sales", "Consulting"],
    photo: IMG + "koko new.jpg",
    detailPhoto: DIMG + "Koko.png",
    logos: [{ src: LOGO + "Kimberly-Clark.avif", alt: "Kimberly-Clark" }],
    tags: ["marketing", "sales", "fmcg", "business", "consulting", "grad program"],
    bestFor: "Marketing, sales, and consulting students. Koko landed 3 combined offers, so she knows exactly how to help you follow the same path.",
    detailed: true,
    lead: "Koko studied Marketing and Environmental Studies at the University of Sydney and became the first-ever international graduate hire at Kimberly-Clark, landing a place in their competitive Marketing and Sales grad program. She was promoted before the program even finished.",
    why: "Koko got her role because she met a mentor who helped her understand how to stand out against every other international and local candidate. Now she wants to give that same advantage to every student in a similar situation.",
    different: "Koko has been a Year 11 and 12 tutor for 7 years. She knows how to explain things in a way people can actually act on, not just understand. She listens first, understands where you are, then gives you practical advice tailored to every stage of your job search.",
  },
  {
    id: "koda", name: "Koda Edrick", intl: "International",
    role: "Software Engineer", company: "Lumi Finance",
    uni: "University of New South Wales", degree: "Bachelor of Computer Science",
    major: "Computer Science", industry: "Software / Tech / Startup", rate: "$40",
    visa: "485 - Temporary Graduate Visa",
    specialiseIn: ["Software Engineering"],
    photo: IMG + "koda new.jpg",
    detailPhoto: DIMG + "Koda Profile.png",
    logos: [{ src: LOGO + "LUMI.png", alt: "Lumi Finance" }],
    tags: ["software engineering", "computer science", "tech", "startup"],
    bestFor: "Software Engineering and tech mentees who want to follow his footsteps and are also introverted.",
    detailed: true,
    lead: "Koda studied Computer Science at UNSW. He did not realise the importance of internships at the time and did no local internships — that did not stop him from securing a software engineering role at a medium-sized fintech firm.",
    why: "He wants to help the next generation of software engineers present themselves well and show their capability in front of employers. He understands the competitiveness and wants to show that you can get a SWE role as an international student with no prior local experience.",
    different: "Koda is naturally an introvert, so he understands first hand how to showcase your skillset and willingness to learn even without the outgoing personality. He does not teach you to fake it — he teaches you to win as yourself.",
  },
  {
    id: "deepika", name: "Deepika Dhulipati", intl: "Local",
    role: "Finance Officer", company: "Dept. of Social Services",
    uni: "University of Sydney", degree: "Bachelor of Commerce",
    major: "Marketing and Finance", industry: "Finance / Consulting", rate: "$40",
    visa: "Domestic",
    specialiseIn: ["Finance", "Consulting"],
    photo: IMG + "deepika new.jpg",
    detailPhoto: DIMG + "Deepika mentor pro.png",
    logos: [{ src: LOGO + "Delioote.png", alt: "Deloitte" }, { src: LOGO + "dss-default-social-media.png", alt: "Dept. of Social Services" }],
    tags: ["finance", "accounting", "consulting", "government", "marketing"],
    bestFor: "Finance and accounting students trying to get into the government sector or a major bank.",
    detailed: true,
    lead: "Deepika studied Marketing and Finance at USYD. She is a domestic student but spent most of her time around peers from international backgrounds. She has interned at Deloitte and now works at the Department of Social Services.",
    why: "Having so many peers from international backgrounds, she witnessed first hand how difficult and rare it is to break into the Australian corporate world. She has made it her mission to help the next generation of graduates get into their ideal roles.",
    different: "As an academic tutor for five years, she knows how to convey concepts in a way students can practically apply. She also has a wide network of professionals and deep industry knowledge in the government sector.",
  },
  {
    id: "samuel", name: "Samuel Kember", intl: "Local",
    role: "Graduate Consultant", company: "Oliver Wyman",
    uni: "University of Sydney", degree: "Bachelor of Commerce (Finance) and Engineering",
    major: "Commerce (Finance) and Engineering", industry: "Consulting / Finance", rate: "$40-50",
    visa: "Domestic", gradYear: "2024",
    specialiseIn: ["Consulting", "Finance", "Engineering"],
    photo: IMG + "samuel kember.png",
    detailPhoto: DIMG + "Samuel kember (ONLY FOR INTERNAL USE) (1).png",
    logos: [{ src: LOGO + "OW_logo_k-white.png", alt: "Oliver Wyman" }, { src: LOGO + "macquarie-bank-limited-logo-black-and-white.png", alt: "Macquarie Bank" }],
    tags: ["consulting", "finance", "engineering", "commerce"],
    bestFor: "Consulting and finance students who want to improve how they communicate and present themselves, not just what they put on paper.",
    detailed: true,
    lead: "Samuel studied Commerce (Finance) and Engineering at the University of Sydney and now works as a Graduate Consultant at Oliver Wyman. He interned at Macquarie Bank and the Defence Department, where he worked on AI-related projects.",
    why: "Samuel was supported by mentors throughout his own journey, including practical coaching that helped him get through consulting recruitment. He wants to give that back and help others navigate the same path.",
    different: "He focuses heavily on soft skills and how you present yourself, not just technical ability. He believes being personable and easy to work with is what truly separates candidates. Expect a natural, conversational session where he first understands your background, personality, and confidence level, then tailors advice to what you actually need.",
  },
  {
    id: "woohee", name: "Woo Hee", intl: "Local",
    role: "Graduate Data Scientist", company: "Commonwealth Bank",
    uni: "University of New South Wales", degree: "Bachelor of Data Science and Decisions",
    major: "Data Science and Decisions", industry: "Tech / Data / Finance", rate: "$60",
    visa: "Domestic", gradYear: "2024",
    specialiseIn: ["Data Science", "Tech", "Finance"],
    photo: IMG + "wohee.jpg",
    detailPhoto: DIMG + "Woohee profile.png",
    logos: [{ src: LOGO + "commbank-beacon-white.webp", alt: "Commonwealth Bank" }, { src: LOGO + "macquarie-bank-limited-logo-black-and-white.png", alt: "Macquarie Bank" }, { src: LOGO + "Grant_Thornton_logo.png", alt: "Grant Thornton" }],
    tags: ["data science", "data", "tech", "finance", "analytics", "banking"],
    bestFor: "Data, tech, or finance students who want honest practical guidance and want to improve how they present themselves and stand out in applications.",
    detailed: true,
    lead: "Woo Hee grew up in Sydney after moving from South Korea and studied Data Science at UNSW. He interned at Macquarie Bank and Grant Thornton, and now works as a Graduate Data Scientist at Commonwealth Bank.",
    why: "Woo Hee understands the challenges international students face, especially language barriers and visa constraints, and wants to support others going through the same journey.",
    different: "He focuses on both emotional support and practical advice, helping mentees understand how to present themselves, communicate effectively, and stand out beyond just grades or experience. Expect him to first understand your situation and goals, then tailor the session to what you actually need, including areas you may be overlooking.",
  },
  {
    id: "jai", name: "Jai Arora", intl: "International",
    role: "Associate", company: "Macquarie",
    uni: "University of New South Wales", degree: "Bachelor of Information Systems",
    major: "Information Systems", industry: "Tech / Finance / Financial Services", rate: "$40",
    visa: "485 - Temporary Graduate Visa", gradYear: "2025",
    specialiseIn: ["Cyber Security", "Financial Services"],
    photo: IMG + "Jai .png",
    detailPhoto: DIMG + "Jai.png",
    logos: [{ src: LOGO + "macquarie-bank-limited-logo-black-and-white.png", alt: "Macquarie" }, { src: LOGO + "pwc white logo.jpg", alt: "PwC" }],
    tags: ["information systems", "tech", "finance", "financial services", "banking", "it", "cyber security", "internship", "return offer"],
    bestFor: "IT and tech students looking to break into financial services or convert an internship into a return offer.",
    detailed: true,
    lead: "Jai is finishing a Bachelor of Information Systems at UNSW and works as an Associate at Macquarie, a role he landed through a direct online application after two years as a casual analyst at PwC.",
    why: "His brother went through the mentoring process, and watching that up close showed him what a real difference it makes. He has also seen enough people struggle to know the gap is real.",
    different: "Jai helps students build something concrete, whether a project, a personal website, or a presence in the right societies, and then connect it back to their story rather than letting it sit as a line on a resume.",
  },
  {
    id: "brendon", name: "Brendon Vo", intl: "Local",
    role: "Early Careers Specialist", company: "InfraBuild",
    uni: "University of Wollongong", degree: "Double Degree, Law and Commerce",
    major: "Human Resources", industry: "HR / Law / Recruitment", rate: "$20",
    visa: "Domestic", gradYear: "2022",
    specialiseIn: ["HR", "Law", "Recruitment"],
    photo: IMG + "Brendon .png",
    detailPhoto: DIMG + "Brendon.png",
    logos: [{ src: LOGO + "Infrabuild.png", alt: "InfraBuild" }],
    tags: ["hr", "human resources", "law", "sales", "manufacturing", "engineering", "finance", "recruitment", "graduate programs"],
    bestFor: "Students aiming for careers in HR, law, sales, manufacturing, engineering, or finance, especially international students who need to build genuine connections and stand out beyond the transactional.",
    detailed: true,
    lead: "Brendon holds a double degree in law and commerce, majoring in HR, from the University of Wollongong and works as an Early Careers specialist at InfraBuild. He built and managed a graduate program from scratch that achieved 100% retention, including visa support for international students.",
    why: "He has a genuine drive to work with graduates, especially those whose confidence has been worn down by repeated rejections. Seeing people in his own network land roles in HR and law clerkships is what keeps him going.",
    different: "His background is on the recruiter side. He built and ran a graduate hiring program from the inside, which means he can teach students how to build connections that go beyond the transactional and actually stick. He uses structured frameworks to help mentees take ownership of their own development, including those who tend to hold back.",
  },
];

export function getMentor(id) {
  return mentors.find((m) => m.id === id);
}
